name: "SAST Analysis Example Action"
author: "Dennis Medeiros"
branding:
   icon: 'shield'
   color: 'green'
   
description: "Receives file and generates output"

inputs:
  vid:
    description: 'Who to greet'
    required: true
    default: 'World'
  vkey:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  targetPath:
      description: "Path to test script"
      default: "target/verademo.war"
      required: true
      
   #policyConfiguration:
   #   description: "Path to test script"
   #   required: true
   #   default: "testMe"
   #baselineFile:
   #   description: "Path to test script"
   #   required: true
   #   default: "testMe"

# outputs:
    # results-file: # id of output
    #  description: "Path to results file"
 
runs:
  #sing: 'docker'
  #mage: 'docker://veracode/api-wrapper-java'
  using: "composite"
  steps:
      - run: echo Hello ${{ inputs.vid }}.
        shell: bash
      - run: echo Hello ${{ inputs.vkey }}.
        shell: bash
      - run: echo Hello ${{ inputs.targetPath }}.
        shell: bash
   # download the Veracode Static Analysis Pipeline scan jar
    # - uses: wei/curl@master
      # with:
        # args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
    # - run: unzip -o pipeline-scan-LATEST.zip

    # - uses: actions/setup-java@v1
      # with:
        # java-version: 1.8
    # - run: java -jar pipeline-scan.jar --veracode_api_id "${{secrets.VERACODE_API_ID}}" --veracode_api_key "${{secrets.VERACODE_API_KEY}}" --fail_on_severity="Very High, High" --file veracode-pipeline-scan-results-to-sarif.zip
      # continue-on-error: true
    # - uses: actions/upload-artifact@v1
      # with:
        # name: ScanResults
        # path: results.json
    # - name: Convert pipeline scan output to SARIF format
      # id: convert
      # uses: veracode/veracode-pipeline-scan-results-to-sarif@master
      # with:
        # pipeline-results-json: results.json
    # - uses: github/codeql-action/upload-sarif@v1
      # with:
       # Path to SARIF file relative to the root of the repository
        # sarif_file: veracode-results.sarif
